### 마일스톤 생성
POST http://localhost:8080/projects/1/tasks/1/milestones
Cookie: SESSION={{session}}
Content-Type: application/x-www-form-urlencoded

title=테스트마일스톤&description=마일스톤설명&status=PLANNED&dueDate=2024-12-31T00:00:00

### 마일스톤 수정
POST http://localhost:8080/projects/1/tasks/1/milestones
Cookie: SESSION={{session}}
Content-Type: application/x-www-form-urlencoded

_method=PUT&title=수정된마일스톤&description=수정된설명&status=IN_PROGRESS&dueDate=2024-12-31T00:00:00

### 마일스톤 삭제
POST http://localhost:8080/projects/1/tasks/1/milestones
Cookie: SESSION={{session}}
Content-Type: application/x-www-form-urlencoded

_method=DELETE